version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - '1433:1433'
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'root.123'
    volumes:
      - sqlserver-data:/var/opt/mssql
    mem_limit: 4g
    mem_reservation: 2g

  backend:
    depends_on:
      - postgres-db
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    env_file: ./.env

volumes:
  sqlserver-data:
    driver: local
