FROM node:21-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./
COPY pnpm-lock.yaml ./

RUN npm install -g pnpm

RUN pnpm install

COPY . .


EXPOSE 3000

CMD ["pnpm", "run", "start:dev"]

