services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - '1433:1433'
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'root.123'
    volumes:
      - sqlserver-data:/var/opt/mssql
    mem_limit: 4g
    mem_reservation: 2g

  task-api:
    depends_on:
      - db
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      ".env"
    ports:
      - "${PORT}:3000" 
    networks:
      - default


volumes:
  sqlserver-data:
    driver: local
