
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: prueba-db-sqlserver
    ports:
      - '${DB_PORT}:1433'
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
      MSSQL_DATABASE: ${DB_NAME}
    volumes:
      - sqlserver-data:/var/opt/mssql
    mem_limit: 4g
    mem_reservation: 2g
    networks:
      - prueba-network
  
  task-api:
    depends_on:
      - db
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      ".env"
    ports:
      - "${PORT}:3000" 
    command: pnpm start:dev
    networks:
      - prueba-network

volumes:
  sqlserver-data:
    driver: local

networks:
  prueba-network:
    driver: bridge